export const pnpmLock = `This lock file is generated by the package manager. It registers the dependency version, location, and integrity hash, for packages installed in a project (in this case, the workspace). Lock files are used to ensure consistent, secure and predictable package installation across machines. The specific lock file type ('pnpm-lock', 'yarn-lock', etc.) is determined by the package manager that was selected for this workspace.

Note that lock files affect the dependency installation in a workspace, but do not affect the components' dependency graph.

Also note, that dependencies between components (as oppose to packages) are always specific and concrete.
A purely component-based project does not require lock files as all component dependencies are concrete (and therefore are "locked").
`;
