import React from 'react';
import { Theme } from './examples/default-theme.demo';
import { ButtonStyledWithCss } from './examples/button-styled-with-css.demo';
import { ButtonStyledWithJs } from './examples/button-styled-with-js.demo';
import { darkThemeOverrides } from './examples/dark-theme.demo';

const Space = () => <div style={{ marginBottom: 25 }} />;

/* uses a theme that was generated by the theme-provider */
export const ButtonsThemedByTheDefaultTheme = () => {
  return (
    <Theme>
      <ButtonStyledWithJs />
      <Space />
      <ButtonStyledWithCss />
    </Theme>
  );
};

/* overrides the default theme with the dark-theme design token values */
export const ButtonsThemedByTheDarkTheme = () => {
  return (
    <Theme overrides={darkThemeOverrides}>
      <ButtonStyledWithJs />
      <Space />
      <ButtonStyledWithCss />
    </Theme>
  );
};
