/* THIS EXAMPLE DEMONSTRATES HOW TO STYLE A COMPONENT WITH CSS TO MAKE IT THEMEABLE */

import React from 'react';

/* style this button using CSS props */
export const ButtonStyledWithCss = () => {
  /*
   * these css props were generated by the `createTheme` funciton. They are made available in the page by the generated Theme component.
   */
  const cssProps = {
    backgroundColor: 'var(--color-background)',
    color: 'var(--color-text)',
    borderColor: 'var(--color-border)',
    padding: 'var(--spacing-medium)',
    fontWeight: 'var(--button-font-weight)',
  };
  return <button style={cssProps}>A Button Styled using CSS Props</button>;
};
